import dotenv from 'dotenv';

dotenv.config();

const {
  NODE_ENV,
  DATABASE,
  DATABASE_PASSWORD,
  PORT_CONFIG,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRATION,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
} = process.env;

const requiredValues = [
  'NODE_ENV',
  'DATABASE',
  'DATABASE_PASSWORD',
  'PORT_CONFIG',
  'ACCESS_TOKEN_SECRET',
  'ACCESS_TOKEN_EXPIRATION',
  'REFRESH_TOKEN_SECRET',
  'REFRESH_TOKEN_EXPIRATION',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
];

for (const value of requiredValues) {
  if (!process.env[value]) {
    console.error(`${value} is required in the .env file`);
    process.exit(1);
  }
}

export {
  NODE_ENV,
  DATABASE,
  DATABASE_PASSWORD,
  PORT_CONFIG,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRATION,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
};
